/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoachGuideRouteImport } from './routes/coach-guide'
import { Route as LineIdRouteImport } from './routes/line.$id'
import { Route as StationCodeRouteImport } from './routes/station.$code'
import { Route as TrainNumberRouteImport } from './routes/train.$number'
import { Route as ApiLiveNetworkRouteImport } from './routes/api/live/network'
import { Route as ApiLiveStationCodeRouteImport } from './routes/api/live/station.$code'
import { Route as ApiLiveTrainNoRouteImport } from './routes/api/live/train.$no'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachGuideRoute = CoachGuideRouteImport.update({
  id: '/coach-guide',
  path: '/coach-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LineIdRoute = LineIdRouteImport.update({
  id: '/line/$id',
  path: '/line/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StationCodeRoute = StationCodeRouteImport.update({
  id: '/station/$code',
  path: '/station/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainNumberRoute = TrainNumberRouteImport.update({
  id: '/train/$number',
  path: '/train/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveNetworkRoute = ApiLiveNetworkRouteImport.update({
  id: '/api/live/network',
  path: '/api/live/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveStationCodeRoute = ApiLiveStationCodeRouteImport.update({
  id: '/api/live/station/$code',
  path: '/api/live/station/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveTrainNoRoute = ApiLiveTrainNoRouteImport.update({
  id: '/api/live/train/$no',
  path: '/api/live/train/$no',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coach-guide': typeof CoachGuideRoute
  '/line/$id': typeof LineIdRoute
  '/station/$code': typeof StationCodeRoute
  '/train/$number': typeof TrainNumberRoute
  '/api/live/network': typeof ApiLiveNetworkRoute
  '/api/live/station/$code': typeof ApiLiveStationCodeRoute
  '/api/live/train/$no': typeof ApiLiveTrainNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coach-guide': typeof CoachGuideRoute
  '/line/$id': typeof LineIdRoute
  '/station/$code': typeof StationCodeRoute
  '/train/$number': typeof TrainNumberRoute
  '/api/live/network': typeof ApiLiveNetworkRoute
  '/api/live/station/$code': typeof ApiLiveStationCodeRoute
  '/api/live/train/$no': typeof ApiLiveTrainNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coach-guide': typeof CoachGuideRoute
  '/line/$id': typeof LineIdRoute
  '/station/$code': typeof StationCodeRoute
  '/train/$number': typeof TrainNumberRoute
  '/api/live/network': typeof ApiLiveNetworkRoute
  '/api/live/station/$code': typeof ApiLiveStationCodeRoute
  '/api/live/train/$no': typeof ApiLiveTrainNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coach-guide'
    | '/line/$id'
    | '/station/$code'
    | '/train/$number'
    | '/api/live/network'
    | '/api/live/station/$code'
    | '/api/live/train/$no'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coach-guide'
    | '/line/$id'
    | '/station/$code'
    | '/train/$number'
    | '/api/live/network'
    | '/api/live/station/$code'
    | '/api/live/train/$no'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coach-guide'
    | '/line/$id'
    | '/station/$code'
    | '/train/$number'
    | '/api/live/network'
    | '/api/live/station/$code'
    | '/api/live/train/$no'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoachGuideRoute: typeof CoachGuideRoute
  LineIdRoute: typeof LineIdRoute
  StationCodeRoute: typeof StationCodeRoute
  TrainNumberRoute: typeof TrainNumberRoute
  ApiLiveNetworkRoute: typeof ApiLiveNetworkRoute
  ApiLiveStationCodeRoute: typeof ApiLiveStationCodeRoute
  ApiLiveTrainNoRoute: typeof ApiLiveTrainNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-guide': {
      id: '/coach-guide'
      path: '/coach-guide'
      fullPath: '/coach-guide'
      preLoaderRoute: typeof CoachGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line/$id': {
      id: '/line/$id'
      path: '/line/$id'
      fullPath: '/line/$id'
      preLoaderRoute: typeof LineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$code': {
      id: '/station/$code'
      path: '/station/$code'
      fullPath: '/station/$code'
      preLoaderRoute: typeof StationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$number': {
      id: '/train/$number'
      path: '/train/$number'
      fullPath: '/train/$number'
      preLoaderRoute: typeof TrainNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/network': {
      id: '/api/live/network'
      path: '/api/live/network'
      fullPath: '/api/live/network'
      preLoaderRoute: typeof ApiLiveNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/station/$code': {
      id: '/api/live/station/$code'
      path: '/api/live/station/$code'
      fullPath: '/api/live/station/$code'
      preLoaderRoute: typeof ApiLiveStationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/train/$no': {
      id: '/api/live/train/$no'
      path: '/api/live/train/$no'
      fullPath: '/api/live/train/$no'
      preLoaderRoute: typeof ApiLiveTrainNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoachGuideRoute: CoachGuideRoute,
  LineIdRoute: LineIdRoute,
  StationCodeRoute: StationCodeRoute,
  TrainNumberRoute: TrainNumberRoute,
  ApiLiveNetworkRoute: ApiLiveNetworkRoute,
  ApiLiveStationCodeRoute: ApiLiveStationCodeRoute,
  ApiLiveTrainNoRoute: ApiLiveTrainNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
